stew/urls.py
from django.contrib import admin
from django.urls import path
from main import views

urlpatterns = [
    path('admin/', admin.site.urls),
    
    #STEW
    path('', views.home, name='home'),
    path('courses/', views.courses, name='courses'),
    path('createcourse/', views.createcourse, name='createcourse'),
    path('joincourse/', views.joincourse, name='joincourse'),
    path('course/<int:course_pk>/', views.coursehome, name='coursehome'),
    
    #Teams
    path('jointeam/', views.jointeam, name='jointeam'),
    path('createteam/<int:course_pk>/<int:team_pk>/', views.createteam, name='createteam'),
    path('team/<int:team_pk>/', views.teamhome, name='teamhome'),
    
    #Meetings
    path('addmeeting/<int:course_pk>/<int:team_pk>/', views.addmeeting, name='addmeeting'),
    path('meetinginfo/<int:meeting_pk>/', views.meetinginfo, name='meetinginfo'),
    path('editmeeting/<int:meeting_pk>/', views.editmeeting, name='editmeeting'),
    
    #Tasks
    path('assigntask/<int:course_pk>/<int:team_pk>/', views.assigntask, name='assigntask'),
    path('viewtask/<int:task_pk>/', views.viewtask, name='viewtask'),
    path('edittask/<int:task_pk>/', views.edittask, name='edittask'),
    path('downloadtaskattachment/<int:task_pk>/', views.downloadtaskattachment, name='downloadtaskattachment'),
    path('addtasksubmission/<int:task_pk>/', views.addtasksubmission, name='addtasksubmission'),
    path('viewtasksubmission/<int:submission_pk>/', views.viewsubmission, name='viewsubmission'),
    path('downloadsubmissionattachment/<int:submission_pk>/', views.downloadsubmissionattachment, name='downloadsubmissionattachment'),
    path('downloadgradingattachment/<int:submission_pk>/', views.downloadgradingattachment, name='downloadgradingattachment'),
    
    #FAQs
    path('faq/', views.faq, name='faq'),
    
    #Account Management
    path('logout/', views.logoutaccount, name='logoutaccount'),
    path('login/', views.loginaccount, name='loginaccount'),
    path('signup/', views.signupaccount, name='signupaccount'),
    path('user/<int:user_pk>/', views.userprofile, name='userprofile'),
]

main/models.py
from django.db import models
from django.utils import timezone
from users.models import CustomUser


# Create your models here.

class Course(models.Model):
    
    name = models.CharField(max_length=100)
    
    join_code = models.CharField(max_length=100, unique=True)
    
    instructor = models.ForeignKey(CustomUser, on_delete=models.CASCADE, related_name="taught_courses")
    
    students = models.ManyToManyField(CustomUser, verbose_name=("Students"), related_name="courses", through="Enrollment")
    
    students_can_make_teams = models.BooleanField(default=False)
    
class Enrollment(models.Model):
    student = models.ForeignKey(CustomUser, on_delete=models.CASCADE, related_name="enrollment")
    course = models.ForeignKey(Course, on_delete=models.CASCADE, related_name="enrollment")
    enrolled_as_ta = models.BooleanField(default=False)
    
class Team(models.Model):
    name = models.CharField(max_length=100)
    
    join_code = models.CharField(max_length=100, unique=True)
    
    members = models.ManyToManyField(CustomUser, verbose_name=("Members"), blank=True, related_name="teams", through='Membership')
    
    course = models.ForeignKey(Course, on_delete=models.CASCADE, related_name="teams")
    
    parent_team = models.ForeignKey('self', on_delete=models.CASCADE, related_name="subteams", null=True, blank=True)
    
class Membership(models.Model):
    student = models.ForeignKey(CustomUser, on_delete=models.CASCADE, related_name="membership")
    team = models.ForeignKey(Team, on_delete=models.CASCADE, related_name="membership")
    
class Task(models.Model):
    name = models.CharField(max_length=100)
    description = models.TextField(max_length=5000, blank=True)
    
    attached = models.FileField(upload_to='main/task_attachments/%Y%m%d', null=True, blank=True)
    
    due_date = models.DateTimeField("Due Date", default=timezone.now, null=True, blank=True)
    assigned_date = models.DateTimeField("Assigned", default=timezone.now)
    course = models.ForeignKey(Course, on_delete=models.CASCADE, related_name="all_tasks")
    
    #This team is the parent team of the teams which would make a submission for the task
    #If null, then it is a course level task
    task_level = models.ForeignKey(Team, on_delete=models.CASCADE, related_name="task_level", null=True)
    
    is_team_task = models.BooleanField(default=False)
    
class TaskSubmission(models.Model):
    task = models.ForeignKey(Task, on_delete=models.CASCADE, related_name="task_submissions")
    
    description = models.TextField(max_length=5000, blank=True)
    
    attached = models.FileField(upload_to='main/task_submissions/', null=True, blank=True)
    
    team = models.ForeignKey(Team, on_delete=models.CASCADE, related_name="submitted_tasks", null=True, blank=True)
    
    submitter = models.ForeignKey(CustomUser, on_delete=models.CASCADE, related_name="submitted_task")
    
    submission_time = models.DateTimeField("Submitted", default=timezone.now)
    
    grade = models.FloatField(null=True, blank=True)
    
    grading_comments = models.TextField(max_length=5000, blank=True)
    
    grading_attached = models.FileField(upload_to='main/task_grading/', null=True, blank=True)
    
    grader = models.ForeignKey(CustomUser, on_delete=models.CASCADE, related_name="graded_tasks", null=True, blank=True)
    
    grade_visible = models.BooleanField(null=True, blank=True, default=True)
    
    is_graded = models.BooleanField(null=True, blank=True, default=False)
    
    
class Meeting(models.Model):
    link = models.URLField(max_length=300)
    memo = models.TextField(max_length=500, blank=True)
    meeting_time = models.DateTimeField("Meeting Time", default=timezone.now)
    is_complete = models.BooleanField(default=False)
    meeting_course = models.ForeignKey(Course, on_delete=models.CASCADE, related_name="meetings")
    meeting_team = models.ForeignKey(Team, on_delete=models.CASCADE, related_name="meetings", null=True, blank=True)
    meeting_host = models.ForeignKey(CustomUser, on_delete=models.CASCADE, related_name="hosted_meetings")

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager, PermissionsMixin
from django.utils.translation import gettext_lazy as _

# Create your models here.

class CustomUserManager(BaseUserManager):
    
    def create_user(self, username, password, email, first_name, last_name, **otherfields):
        if not email:
            raise ValueError(_('You must provide an email address'))
        if not first_name:
            raise ValueError(_('You must provide your first name'))
        if not last_name:
            raise ValueError(_('You must provide your last name'))
        
        email = self.normalize_email(email)
        user = self.model(email=email, username=username, first_name=first_name, last_name=last_name, **otherfields)
        user.set_password(password)
        user.save()
        return user
    
    def create_superuser(self, username, password, email, first_name, last_name, **otherfields):
        otherfields.setdefault('is_staff', True)
        otherfields.setdefault('is_superuser', True)
        otherfields.setdefault('is_active', True)
        otherfields.setdefault('status', 'admin')
        
        if otherfields.get('is_staff') is not True:
            raise ValueError(_('Superuser must have is_staff=True'))
        if otherfields.get('is_superuser') is not True:
            raise ValueError(_('Superuser must have is_superuser=True'))
        
        return self.create_user(username, password, email, first_name, last_name, **otherfields)
            

class CustomUser(AbstractBaseUser, PermissionsMixin):
    
    username = models.CharField(max_length=150, unique=True)
    USERNAME_FIELD = "username"
    
    email = models.EmailField(_("email address"))
    EMAIL_FIELD = "email"
    
    STATUS = (
        ('student', 'student'),
        ('teacher','teacher'),
        ('admin', 'admin'),
    )
    status = models.CharField(max_length=100, choices=STATUS, default='student')
    
    first_name = models.CharField(max_length=150)
    last_name = models.CharField(max_length=150)
    is_staff = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)
    
    description = models.TextField('Description', max_length=600, default='', blank=True)
    
    profile_picture = models.ImageField(upload_to='users/images/', null=True, blank=True)
    
    REQUIRED_FIELDS = ['email', 'first_name', 'last_name']
    
    objects = CustomUserManager()
    
    def __str__(self):
        return self.username
    

main/forms.py
from django.forms import ModelForm
from .models import Course, Team, Meeting, Task

class CourseForm(ModelForm):
    class Meta:
        model = Course
        fields = ['name', 'join_code']
        
class TeamForm(ModelForm):
    class Meta:
        model = Team
        fields = ['name', 'join_code']
        
class MeetingForm(ModelForm):
    class Meta:
        model = Meeting
        fields = ['link', 'memo', 'meeting_time']
        
class TaskForm(ModelForm):
    class Meta:
        model = Task
        fields = ['name','description','attached','due_date','is_team_task']

main/templates/main/addmeeting.html
{% extends 'main/base.html' %}

{% block content %}

<h1>Add Meeting</h1>

<h2>{{ error }}</h2>

<form method="POST">
    {% csrf_token %}

    <p>
        <label for="id_link">Link:</label>
        <input type="url" name="link" maxlength="300" required="" id="id_link">
    </p>

    <p>
        <label for="id_memo">Memo:</label>
        <textarea name="memo" cols="40" rows="10" maxlength="500" id="id_memo"></textarea>
    </p>

    <p>
        <label for="id_meeting_time">Meeting Time:</label>
        <input type="datetime-local" name="meeting_time" value="{{time|date:'Y-m-d'}}T{{time|date:'H:i'}}" required="" id="id_meeting_time">
    </p>


<button type="submit">Add</button>
</form>

{% endblock %}

main/templates/main/addtasksubmission.html
{% extends 'main/base.html' %}

{% block content %}

<h1>Submit Task</h1>

<h2>{{ error }}</h2>

<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}

    <p>
        <label for="id_description">Description:</label>
        <textarea name="description" cols="40" rows="10" maxlength="5000" id="id_description"></textarea>   
    </p>
    
    <p>
        <label for="id_attached">Attachment:</label>
        <input type="file" name="attached" id="id_attached"> 
    </p>

    <p>
        <label for="id_team">Submitting Team:</label>

        <select name="team" required="" id="id_team">
            <option value="0" selected="selected">Myself</option>
            {% for team in teams %}
            <option value={{team.id}}>{{team.name}}</option>
            {% endfor %}

        </select>
    </p>

    <button type="submit">Save</button>
</form>



{% endblock %}

main/templates/main/base.html
{% if user.is_authenticated %}

Logged in as {{ user.username }}

<a href="{% url 'home' %}">Home</a>
<a href="{% url 'courses' %}">Courses</a>

<form action="{% url 'logoutaccount' %}" method="POST">
    {% csrf_token %}
    <button type="submit">Logout</button>
</form>


{% else %}

<a href="{% url 'home' %}">Home</a>
<a href="{% url 'signupaccount' %}">Signup</a>
<a href="{% url 'loginaccount' %}">Login</a>

{% endif %}

<br>
<br>

{% block content %} {% endblock %}

main/templates/main/courses.html
{% extends 'main/base.html' %}

{% block content %}

Courses

{% if is_teacher %}
<a href="{% url 'createcourse' %}">Create Course</a>
{% endif %}

<br>

<a href="{% url 'joincourse' %}">Join Course</a>

<br>

<h1>Enrolled Courses</h1>
<ul>
    {% for course in enrolled_courses %}
    <li>
        <a href="{% url 'coursehome' course.id %}">
            {{course.name}}
        </a>
    </li>
    {% endfor %}
</ul>

<br>

{% if is_teacher %}

<h1>Taught Courses</h1>
<ul>
    {% for course in taught_courses %}
    <li>
        <a href="{% url 'coursehome' course.id %}">
            {{course.name}}
        </a>
    </li>
    {% endfor %}
</ul>

{% endif %}

{% endblock %}

main/templates/main/createcourse.html
{% extends 'main/base.html' %}

{% block content %}

<h1> Create Course </h1>

<h2>{{ error }}</h2>

<form method="POST">
    {% csrf_token %}

<p>
    <label for="id_coursename">Course Name:</label>
    <input type="text" name="name" autofocus autocapitalize="none" autocomplete="course name" maxlength="100" required id="id_coursename">
</p>
<p>
    <label for="id_coursecode">Course Code:</label>
    <input type="text" name="join_code" maxlength="100" required id="id_coursecode">
</p>

<button type="submit">Create</button>
</form>

{% endblock %}

main/templates/main/createteam.html
{% extends 'main/base.html' %}

{% block content %}

<h1> Create Team </h1>

<h2>{{ error }}</h2>

<form method="POST">
    {% csrf_token %}

<p>
    <label for="id_teamname">Team Name:</label>
    <input type="text" name="name" autofocus autocapitalize="none" autocomplete="team name" maxlength="100" required id="id_teamname">
</p>
<p>
    <label for="id_teamcode">Team Code:</label>
    <input type="text" name="join_code" maxlength="100" required id="id_teamcode">
</p>

<button type="submit">Create</button>
</form>

{% endblock %}

main/templates/main/edittask.html
{% extends 'main/base.html' %}

{% block content %}

<h1>Edit Task</h1>

<h2>{{ error }}</h2>

<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}

    <p>
        <label for="id_name">Name:</label>
        <input type="text" name="name" value="{{task.name}}" maxlength="100" required="" id="id_name">    
    </p>

    <p>
        <label for="id_description">Description:</label>
        <textarea name="description" cols="40" rows="10" maxlength="5000" id="id_description">{{task.description}}</textarea>   
    </p>
    
    <p>
        <label for="id_attached">New Attachment (Will overide the old attachment):</label>
        <input type="file" name="attached" id="id_attached"> 
    </p>

    <p>
        Previous Attachment: <a href="{% url 'downloadtaskattachment' task.id %}" download>{{task.attached.name}}</a>
    </p>

    <p>
        <label for="id_due_date">Due Date:</label>
        <input type="datetime-local" name="due_date" value="{{task.due_date|date:'Y-m-d'}}T{{task.due_date|date:'H:i'}}" id="id_due_date">
    </p>

    <p>
        <label for="id_is_team_task">Is team task:</label>
        <select name="is_team_task" id="id_is_team_task"> 
            {% if task.is_team_task %}
            <option value="True" selected="selected">Team Task</option>
            <option value="False">Individual Task</option>
            {% else %}
            <option value="True">Team Task</option>
            <option value="False" selected="selected">Individual Task</option>
            {% endif %}
        </select>

    </p>

    <button type="submit">Save</button>
</form>



{% endblock %}

main/templates/main/faq.html
{% extends 'main/base.html' %}

{% block content %}

<h1> FAQ </h1>

<h3>1. How do I create an account?</h3>
<p>To create an account, visit our website and look for the link that says "Sign Up". You'll need to provide your personal information, such as your name, email address, and a password. Follow the on-screen instructions to complete the registration process. </p>

<h3>2. What should I do if I forgot my password or username?</h3>
<p>If you forget your password or username, please contact site administrator and provide all the following information used during registration: First Name, Last Name, Email Address. You are welcome to provide other information as well if you believe it will be useful for recovering your account.</p>

<h3>3. How do I submit my homework task?</h3>
<p>Homework tasks can be submitted through our platform. Log in to your account, navigate to the relevant task assignment, and follow the instructions provided for submitting your homework task. This might involve uploading files, typing in text, or following other guidelines provided by your instructor.</p>

<h3>4. What file formats are accepted for homework task submission?</h3>
<p>Accepted file formats for homework submission can vary, but commonly supported formats include PDF, Microsoft Word documents (DOC or DOCX), and sometimes image files (JPG, PNG). Always check the specific requirements for each assignment, as instructors may have preferences. If you need to submit multiple files at once, do so using a .zip file.
</p>

<h3>5. How can I confirm my homework task has been successfully submitted?</h3>
<p>Once a task has been submitted, a task submission will appear for that task on the page with its task description. If in doubt, reach out to your instructor or course administrator for confirmation.</p>

<h3>6. How can I check the status or feedback of my submitted homework task?</h3>
<p>To check the status or feedback of a submitted homework task, log in to your account and access the specific task submission page. Instructors typically provide grades and feedback through the platform. Look for your grade and feedback above the task submission comments section. If it is not there, either the submission has not been graded yet, or the instructor has not marked the grade as visible.</p>

<h3>7. How can I schedule a meeting with my professor or a classmate?</h3>
<p>If your instructor has allowed you to do so, you can create a team where you can invite your classmate or professor and create a meeting there. Reach out to your desired contact and propose a meeting time that works for both parties. Remember, you can always edit the meeting time if you need to.</p>

{% endblock %}

main/templates/main/index.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">

<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
<title></title>
<meta name="keywords" content="">
	<meta name="robots" content="index, follow, max-image-preview:large, max-snippet:-1, max-video-preview:-1">
<meta name="description" content="">
<link href="http://fonts.googleapis.com/css?family=Source+Sans+Pro:200,300,400,600,700,900%7CQuicksand:400,700%7CQuestrial" rel="stylesheet">
<link href="default.css" rel="stylesheet" type="text/css" media="all">
<link href="fonts.css" rel="stylesheet" type="text/css" media="all">


</head>
<body>
<div id="header-wrapper">
	<div id="header" class="container">
		<div id="logo">
        	<span class="icon icon-cog"></span>
			<h1><a href="#">STEW</a></h1>
		</div>
		<div id="menu">
			<ul>
				<li class="active"><a href="#" accesskey="1" title="">Homepage</a></li>
				<li><a href="#" accesskey="2" title="">Moodle</a></li>
				<li><a href="#" accesskey="3" title="">Zoom</a></li>
				<li><a href="#" accesskey="4" title="">Calender</a></li>
				<li><a href="#" accesskey="5" title="">Class</a></li>
			</ul>
		</div>
	</div>
</div>
<div class="wrapper">
	<div id="banner" class="container"><img src="images/OAKLAND.jpeg" width="1200" height="500" alt=""></div>
	<div id="welcome" class="container">
    	
<div class="title">
	  <h2>Welcome to STEW</h2>
		</div>
		<p>STEW<strong>is</strong>, all you will need for academic success <a href="https://zoom.us/signin#/login" rel="nofollow">Create Zoom meetings right from the dashboard</a>. Need to access moodle  <a href="https://moodle.oakland.edu/login/index.php"> Moodle link</a>. NEED to access the oakland university hompage <a href="https://www.oakland.edu">OAKLAND UNIVERSITY HOMEPAGE</a>???????????????????</p>
	</div>
	<div id="three-column" class="container">
		<div><span class="arrow-down"></span></div>
		<div id="tbox1">
			<div class="title">
				<h2>INFO 1</h2>
			</div>
			<p> ADD info </p>
			<a href="#" class="button">Learn More</a> </div>
		<div id="tbox2">
			<div class="title">
				<h2>INFO 2</h2>
			</div>
			<p> INFO 2 HERE</p>
			<a href="#" class="button">Learn More</a> </div>
		<div id="tbox3">
			<div class="title">
				<h2>INFO 3</h2>
			</div>
			<p>ADD info 3</p>
			<a href="#" class="button">Learn More</a> </div>
	</div>
	<div id="portfolio" class="container">
		<div class="column1">
			<div class="box">
			  <h3>MORE0</h3>
				<p>????????????????</p>
		  <a href="#" class="button button-small">MORE0 Button </a> </div>
		</div>
		<div class="column2">
			<div class="box">
			  <h3>MORE1</h3>
				<p>?????</p>
		  <a href="#" class="button button-small">MORE1 button</a> </div>
		</div>
		<div class="column3">
			<div class="box">
			  <h3>MORE2</h3>
				<p>????????</p>
		  <a href="#" class="button button-small">MORE2 BUTTON</a> </div>
		</div>
		<div class="column4">
			<div class="box">
			  <h3>MORE3</h3>
				<p>?????????</p>
		  <a href="#" class="button button-small">MORE3 button</a> </div>
		</div>
	</div>
</div>
<div id="footer">
	<div class="container">
		<div class="fbox1">
		<span class="icon icon-map-marker"></span>
			<span> 318 Meadow Brook Rd, Rochester
			<br>MI 48309</span>
		</div>
		<div class="fbox1">
			<span class="icon icon-phone"></span>
			<span>
				Telephone: (248) 370-2100
			</span>
		</div>
		<div class="fbox1">
			<span class="icon icon-envelope"></span>
			<span>ENTER EMAIL HERE </span>
		</div>
	</div>
</div>
<div id="copyright">
	<ul class="contact">
		<li><a href="#" class="icon icon-twitter"><span>Twitter</span></a></li>
		<li><a href="#" class="icon icon-facebook"><span></span></a></li>
		<li><a href="#" class="icon icon-dribbble"><span>Pinterest</span></a></li>
		<li><a href="#" class="icon icon-tumblr"><span>Google+</span></a></li>
		<li><a href="#" class="icon icon-rss"><span>Pinterest</span></a></li>
	</ul>
</div>

</body>
</html>

main/templates/main/joincourse.html
{% extends 'main/base.html' %}

{% block content %}

<h1> Join Course </h1>

<h2>{{ error }}</h2>

<form method="POST">
    {% csrf_token %}

<p>
    <label for="id_coursecode">Course Code:</label>
    <input type="text" name="join_code" maxlength="100" required id="id_coursecode">
</p>

<button type="submit">Join</button>
</form>

{% endblock %}

main/templates/main/loginaccount.html
{% extends 'main/base.html' %}

{% block content %}

<h1> Login </h1>

<h2>{{ error }}</h2>

<form method="POST">
    {% csrf_token %}

<p>
    <label for="id_username">Username:</label>
    <input type="text" name="username" autofocus autocapitalize="none" autocomplete="username" maxlength="150" required id="id_username">

</p>
<p>
    <label for="id_password">Password:</label>
    <input type="password" name="password" autocomplete="current-password" maxlength="150" required id="id_password">

</p>

<button type="submit">Login</button>
</form>

<p>
    <a href="{% url 'signupaccount' %}">Don't have an account? Sign up.</a>
</p>

{% endblock %}

main/templates/main/signupaccount.html
{% extends 'main/base.html' %}

{% block content %}

<h1> Signup </h1>

<h2>{{ error }}</h2>

<form method="POST">
    {% csrf_token %}

<p>
    <label for="id_username">Username:</label>
    <input type="text" name="username" autofocus autocapitalize="none" autocomplete="username" maxlength="150" required id="id_username">
</p>
<p>
    <label for="id_email">Email:</label>
    <input type="email" name="email" autocapitalize="none" autocomplete="username" maxlength="150" required id="id_email">
</p>

<p>
    <label for="id_fname">First Name:</label>
    <input type="text" name="first_name" autocapitalize="none" autocomplete="username" maxlength="150" required id="id_fname">
</p>
<p>
    <label for="id_lname">Last Name:</label>
    <input type="text" name="last_name" autocapitalize="none" autocomplete="username" maxlength="150" required id="id_lname">
</p>

<p>
    <label for="id_password1">Password:</label>
    <input type="password" name="password1" autocomplete="current-password" maxlength="150" required id="id_password1">
</p>
<p>
    <label for="id_password2">Confirm Password:</label>
    <input type="password" name="password2" autocomplete="current-password" maxlength="150" required id="id_password2">
</p>
<p>
    <label for="id_my_role">I am a(n) </label>
    <select  name="my_role" required id="id_my_role">
        <option value="student" selected="selected">Student</option>
        <option value="instructor">Instructor</option>
    </select>
</p>

<button type="submit">Sign Up</button>
</form>

<p>
    <a href="{% url 'loginaccount' %}">Already have an account? Login.</a>
</p>

{% endblock %}

main/templates/main/userprofile.html
{% extends 'main/base.html' %}

{% block content %}

<h2>{{ error }}</h2>

<h1>{{ userprofile.first_name }} {{ userprofile.last_name }}</h1>





{% endblock %}

main/templates/main/viewtask.html
{% extends 'main/base.html' %}

{% block content %}

<h1>Task</h1>

<h2>{{ error }}</h2>

<h2>{{ task.name }}</h2>

<p>{{ task.description }}</p>

{% if task.attached %}
Attachment: <a href="{% url 'downloadtaskattachment' task.id %}" download>{{task.attached.name}}</a>
{% endif %}

<br>

{% if task.task_level == null and task.course.instructor.id == request.user.id %}
<a href="{% url 'edittask' task.id %}">
    Edit Task
</a>
{% endif %}
{% if task.task_level != null %}
<a href="{% url 'edittask' task.id %}">
    Edit Task
</a>
{% endif %}

<h3>Task Submissions:</h3>

<ul>
    {% for submission in submissions.all %}
    <li>
        <a href="{% url 'viewsubmission' submission.id %}">
            {% if submission.team %}
            {{submission.team.name}}: {{submission.submitter.first_name}} {{submission.submitter.last_name}}
            {% else %}
            {{submission.submitter.first_name}} {{submission.submitter.last_name}}
            {% endif %}
        </a>
    </li>
    {% endfor %}
</ul>

<a href="{% url 'addtasksubmission' task.id %}">
    Add Submission
</a>


{% endblock %}